[default]
locale = "en-us"
unicode = false

[files]
ignore-hidden = false
extend-exclude = [
    ".git", # needed because we 'ignore-hidden'
    # already submitted assignments
    "homework{1,2,3}"
]
